from button_objects.button_objects_classic import *
def appear_classic():
	button_1.grid(row=6, column=1, sticky="NSEW")
	button_2.grid(row=6, column=2, sticky="NSEW")
	button_3.grid(row=6, column=3, sticky="NSEW")
	button_4.grid(row=5, column=1, sticky="NSEW")
	button_5.grid(row=5, column=2, sticky="NSEW")
	button_6.grid(row=5, column=3, sticky="NSEW")
	button_7.grid(row=4, column=1, sticky="NSEW")
	button_8.grid(row=4, column=2, sticky="NSEW")
	button_9.grid(row=4, column=3, sticky="NSEW")
	button_0.grid(row=7, column=2, sticky="NSEW")
	button_pi.grid(row=7, column=1, sticky="NSEW")
	button_e.grid(row=7, column=3, sticky="NSEW")


	button_matrix.grid(row=1, column=1, sticky="NSEW")
	button_clear_entry.grid(row=1, column=3, sticky="NSEW")
	button_backspace.grid(row=1, column=4, sticky="NSEW")
	button_add.grid(row=6, column=4, sticky="NSEW")
	button_subtract.grid(row=5, column=4, sticky="NSEW")
	button_multiply.grid(row=4, column=4, sticky="NSEW")
	button_divide.grid(row=3, column=4, sticky="NSEW")
	button_modulo.grid(row=2, column=4, sticky="NSEW")
	button_equal.grid(row=7, column=4, sticky="NSEW")

	button_apow2.grid(row=2, column=0, sticky="NSEW")

	button_abs.grid(row=2, column=2, sticky="NSEW")
	button_exp.grid(row=2, column=3, sticky="NSEW")
	button_factorial.grid(row=3, column=3, sticky="NSEW")
	button_root.grid(row=3, column=0, sticky="NSEW")
	button_apowb.grid(row=4, column=0, sticky="NSEW")
	button_10powa.grid(row=5, column=0, sticky="NSEW")
	button_log.grid(row=6, column=0, sticky="NSEW")
	button_ln.grid(row=7, column=0, sticky="NSEW")
	button_1_a.grid(row=2, column=1, sticky="NSEW")
	button_plus_min.grid(row=3, column=1, sticky="NSEW")
	button_comma.grid(row=3, column=2, sticky="NSEW")
